name: Get Unity License (.alf)

on:
  workflow_dispatch:

jobs:
  get-alf:
    name: Generate Unity .alf file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Request Unity activation file
        id: get-activation-file
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2022.3.60f1

      - name: Upload .alf artifact
        uses: actions/upload-artifact@v4
        with:
          name: unity-activation-file
          path: ${{ steps.get-activation-file.outputs.filePath }}
          retention-days: 3
